
singularities:
    # These are created using: envs/get_cointainers.sh
    gatk3:      "/data/sifs/pgx_module/gatk3.simg"
    gatk4:      "/data/sifs/gatk/gatk_4.2.5.0.sif"
    rmarkdown:  "/data/sifs/pgx_module/rmarkdown.simg"
    samtools:   "/data/sifs/pgx_module/samtools.simg"
    get_target: "/data/sifs/pgx_module/target_variants_python.simg"

table_data:
    target_regions:        "data/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"
    # target_regions:        "data/genomic_regions/DPYD_CNV98_NM_XXX.bed"
    target_rsid:           "data/genomic_regions/target_rsid.bed"
    haplotype_definitions: "data/haplotypes/haplotype_definitions.csv"
    hidden_haplotypes:     "data/haplotypes/hidden_haplotypes.csv"

clinical_data:
    clinical_guidelines:    "data/guidelines/clinical_guidelines.csv"
    haplotype_activity:     "data/guidelines/haplotype_activity_score.csv"
    interacting_guidelines: "data/guidelines/interaction_guidelines.csv"

reference_fasta: "/data/reference_genomes/hg19/hg19/genome.fa"
dbsnp: "/data/reference_genomes/dbsnp_138.hg19.vcf"

## NOTE: Adjust input location based on where the input bams are located
bam_location: "/home/lauri/Desktop/pgx_dev/our_fork/pgx/alignment/bwa_mem/HD832_T.bam"

# Contact information
name: "Person Persson"
adress: "Gatuvägen stadsplatsen 81, 54321"
mail: "me@mymail.me"
phone: "070 123 45 78"
